# Generated by Django 2.1.1 on 2018-11-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0002_auto_20181107_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='avatar',
        ),
    ]
